/**
 * Demo seed data for Nablus Road Contracting (Dubai).
 * Used for branding fallbacks, sample screens, and create-company prefills.
 */
export const NABLUS_COMPANY = {
  shortName: 'NABLUS',
  business_name: 'Nablus Road Contracting',
  business_name_arabic: 'نابلس لمقاولات الطرق',
  phone_no: '+971 4 338 2140',
  alternate_business_no: '+971 50 612 8840',
  email: 'info@nablusroad.ae',
  alternate_email: 'accounts@nablusroad.ae',
  address1: 'Warehouse 14, Al Quoz Industrial Area 3',
  address2: 'Near Industrial Area Roundabout',
  po_box: 'P.O. Box 118820',
  city: 'Dubai',
  emirates: 1, // Dubai
  country: 1, // UAE
  license_number: 'CN-789456',
  license_type: 'Commercial',
  issued_by: 'Dubai Economy and Tourism',
  license_expiry: '2027-12-31',
  activity: 'Road Contracting, Asphalt & Civil Works',
  legal_type: 'LLC',
  owner_name: 'Khalid Nablus',
  owner_nationality: 'Jordanian',
  owner_emirates_id: '784-1985-1234567-1',
  tax_registration_number: '100456789012345',
  vat_registered: true,
  website: 'www.nablusroad.ae',
  currency: 'AED',
} as const;

export const NABLUS_PARTIES_SAMPLE = [
  ['Party Name', 'Party Type', 'Mobile Number', 'Email', 'TRN', 'Billing Address', 'Shipping Address', 'Opening Balance'],
  ['Dubai Municipality - Roads', 'Customer', '97143122222', 'roads@dm.gov.ae', '100111222333444', 'Dubai Municipality HQ, Deira, Dubai', 'Dubai Municipality HQ, Deira, Dubai', '125000.00'],
  ['RTA Dubai', 'Customer', '97148000000', 'procurement@rta.ae', '100222333444555', 'Roads & Transport Authority, Dubai', 'RTA HQ, Dubai', '85000.00'],
  ['Emaar Properties PJSC', 'Customer', '97143668888', 'contracts@emaar.ae', '100333444555666', 'Emaar Square, Downtown Dubai', 'Emaar Square, Downtown Dubai', '42000.00'],
  ['Al Futtaim Building Materials', 'Vendor', '97142955555', 'sales@afbm.ae', '100444555666777', 'Al Quoz Industrial Area, Dubai', 'Al Quoz Industrial Area, Dubai', '18000.00'],
  ['National Asphalt Co. LLC', 'Vendor', '97143321000', 'orders@nationalasphalt.ae', '100555666777888', 'Jebel Ali Industrial, Dubai', 'Jebel Ali Industrial, Dubai', '9500.00'],
];

export const NABLUS_ITEMS_SAMPLE = [
  ['Item Name', 'Item Code', 'Item Type', 'Sales Price', 'Purchase Price', 'Unit', 'HSN Code', 'Description'],
  ['Asphalt Mix Hot (Base Course)', 'ASP-BASE-01', 'Product', '285.00', '220.00', 'TON', '27150000', 'Hot mix asphalt for road base course'],
  ['Asphalt Mix Hot (Wearing Course)', 'ASP-WEAR-01', 'Product', '320.00', '250.00', 'TON', '27150000', 'Wearing course asphalt for finished roads'],
  ['Crushed Aggregate 20mm', 'AGG-20MM', 'Product', '45.00', '32.00', 'TON', '25171000', '20mm crushed stone aggregate'],
  ['Bitumen 60/70', 'BIT-6070', 'Product', '1850.00', '1620.00', 'TON', '27132000', 'Penetration grade bitumen 60/70'],
  ['Road Marking Paint - White', 'RMP-WHT', 'Product', '85.00', '62.00', 'LTR', '32089090', 'Thermoplastic road marking paint'],
  ['Concrete Grade C40', 'CON-C40', 'Product', '280.00', '235.00', 'M3', '68109900', 'Ready-mix concrete C40'],
  ['Steel Rebar 16mm', 'STL-16MM', 'Product', '3200.00', '2850.00', 'TON', '72142000', 'Deformed steel reinforcement bars'],
  ['Road Construction Labour', 'SVC-LABOUR', 'Service', '55.00', '0.00', 'HRS', '998311', 'Skilled site labour charge'],
  ['Asphalt Paving Service', 'SVC-PAVE', 'Service', '18.50', '0.00', 'M2', '998311', 'Machine asphalt paving per sq.m'],
  ['Site Survey & Setting Out', 'SVC-SURVEY', 'Service', '2500.00', '0.00', 'JOB', '998311', 'Topographic survey and setting out'],
];

export const NABLUS_EMPLOYEES = [
  {
    basicInfo: {
      firstName: 'Omar',
      lastName: 'Al Hashimi',
      workEmail: 'omar.hashimi@nablusroad.ae',
      mobileNumber: '0508123340',
      gender: 'Male',
      dob: '1986-04-18',
      age: 40,
      nationality: 'Emirati',
      emiratesId: '784-1986-4455667-1',
      passportNumber: 'C1122334',
      molId: '301402503',
      workPermitNumber: 'WP778899',
      visaExpiry: '2027-08-31',
      laborCardNumber: 'LC556677',
      employeeId: 'NRC001',
      joiningDate: '2019-03-01',
      confirmationDate: '2019-09-01',
      contractType: 'Unlimited',
      emirate: 'Dubai',
      designation: 'Project Manager',
      department: 'Projects',
      leaveAllowed: 30,
      totalLeaves: 30,
      addressLine: 'Villa 22, Al Barsha 2',
      city: 'Dubai',
      state: 'Dubai',
      pinCode: '00000',
    },
    salaryDetails: {
      annualCTC: 288000,
      earnings: [
        { salaryComponent: 'Basic', monthlyAmount: 12000 },
        { salaryComponent: 'HRA', monthlyAmount: 6000 },
        { salaryComponent: 'Transport Allowance', monthlyAmount: 2000 },
        { salaryComponent: 'Site Allowance', monthlyAmount: 4000 },
      ],
    },
    paymentDetails: {
      paymentMode: 'Bank Transfer',
      bankDetails: {
        accountHolderName: 'Omar Al Hashimi',
        bankName: 'Emirates NBD',
        iban: 'AE070331234567890123456',
        routingNumber: '110000',
        accountType: 'Current',
        wpsNumber: 'WPS778801',
      },
    },
  },
  {
    basicInfo: {
      firstName: 'Hassan',
      lastName: 'Mansour',
      workEmail: 'hassan.mansour@nablusroad.ae',
      mobileNumber: '0556342210',
      gender: 'Male',
      dob: '1990-09-22',
      age: 35,
      nationality: 'Egyptian',
      emiratesId: '784-1990-7788990-2',
      passportNumber: 'A9988776',
      molId: '402503604',
      workPermitNumber: 'WP445566',
      visaExpiry: '2026-11-15',
      laborCardNumber: 'LC334455',
      employeeId: 'NRC002',
      joiningDate: '2021-06-15',
      confirmationDate: '2021-12-15',
      contractType: 'Limited',
      emirate: 'Dubai',
      designation: 'Site Supervisor',
      department: 'Site Operations',
      leaveAllowed: 30,
      totalLeaves: 30,
      addressLine: 'Apt 308, International City',
      city: 'Dubai',
      state: 'Dubai',
      pinCode: '00000',
    },
    salaryDetails: {
      annualCTC: 144000,
      earnings: [
        { salaryComponent: 'Basic', monthlyAmount: 6000 },
        { salaryComponent: 'HRA', monthlyAmount: 3000 },
        { salaryComponent: 'Transport Allowance', monthlyAmount: 1000 },
        { salaryComponent: 'Site Allowance', monthlyAmount: 2000 },
      ],
    },
    paymentDetails: {
      paymentMode: 'Bank Transfer',
      bankDetails: {
        accountHolderName: 'Hassan Mansour',
        bankName: 'Mashreq Bank',
        iban: 'AE080331234567890987654',
        routingNumber: '120000',
        accountType: 'Savings',
        wpsNumber: 'WPS778802',
      },
    },
  },
  {
    basicInfo: {
      firstName: 'Priya',
      lastName: 'Nair',
      workEmail: 'priya.nair@nablusroad.ae',
      mobileNumber: '0527789012',
      gender: 'Female',
      dob: '1993-01-10',
      age: 33,
      nationality: 'Indian',
      emiratesId: '784-1993-1122334-3',
      passportNumber: 'Z5566778',
      molId: '503604705',
      workPermitNumber: 'WP223344',
      visaExpiry: '2026-05-20',
      laborCardNumber: 'LC112233',
      employeeId: 'NRC003',
      joiningDate: '2022-02-01',
      confirmationDate: '2022-08-01',
      contractType: 'Limited',
      emirate: 'Dubai',
      designation: 'Quantity Surveyor',
      department: 'Estimation',
      leaveAllowed: 30,
      totalLeaves: 30,
      addressLine: 'Flat 12B, Discovery Gardens',
      city: 'Dubai',
      state: 'Dubai',
      pinCode: '00000',
    },
    salaryDetails: {
      annualCTC: 168000,
      earnings: [
        { salaryComponent: 'Basic', monthlyAmount: 7000 },
        { salaryComponent: 'HRA', monthlyAmount: 3500 },
        { salaryComponent: 'Transport Allowance', monthlyAmount: 1500 },
        { salaryComponent: 'Other Allowances', monthlyAmount: 2000 },
      ],
    },
    paymentDetails: {
      paymentMode: 'Bank Transfer',
      bankDetails: {
        accountHolderName: 'Priya Nair',
        bankName: 'ADCB',
        iban: 'AE090331234567891112233',
        routingNumber: '130000',
        accountType: 'Savings',
        wpsNumber: 'WPS778803',
      },
    },
  },
  {
    basicInfo: {
      firstName: 'Mohammed',
      lastName: 'Yousef',
      workEmail: 'mohammed.yousef@nablusroad.ae',
      mobileNumber: '0564457788',
      gender: 'Male',
      dob: '1988-07-05',
      age: 37,
      nationality: 'Jordanian',
      emiratesId: '784-1988-3344556-4',
      passportNumber: 'J4455667',
      molId: '604705806',
      workPermitNumber: 'WP889900',
      visaExpiry: '2027-01-10',
      laborCardNumber: 'LC998877',
      employeeId: 'NRC004',
      joiningDate: '2020-09-10',
      confirmationDate: '2021-03-10',
      contractType: 'Unlimited',
      emirate: 'Dubai',
      designation: 'Plant Operator',
      department: 'Plant & Machinery',
      leaveAllowed: 30,
      totalLeaves: 30,
      addressLine: 'Camp Room 14, Al Quoz Labour Camp',
      city: 'Dubai',
      state: 'Dubai',
      pinCode: '00000',
    },
    salaryDetails: {
      annualCTC: 72000,
      earnings: [
        { salaryComponent: 'Basic', monthlyAmount: 3500 },
        { salaryComponent: 'HRA', monthlyAmount: 1000 },
        { salaryComponent: 'Transport Allowance', monthlyAmount: 500 },
        { salaryComponent: 'Site Allowance', monthlyAmount: 1000 },
      ],
    },
    paymentDetails: {
      paymentMode: 'Bank Transfer',
      bankDetails: {
        accountHolderName: 'Mohammed Yousef',
        bankName: 'Emirates Islamic',
        iban: 'AE100331234567894445566',
        routingNumber: '140000',
        accountType: 'Savings',
        wpsNumber: 'WPS778804',
      },
    },
  },
];

export const NABLUS_ATTENDANCE = [
  {
    employeeId: 'NRC001',
    records: [
      { date: '2026-09-01', status: 'Present', inTime: '07:30 AM', outTime: '06:00 PM', workedHours: '10.5', remarks: 'Sheikh Zayed Rd site' },
      { date: '2026-09-02', status: 'Present', inTime: '07:25 AM', outTime: '06:05 PM', workedHours: '10.67', remarks: '' },
      { date: '2026-09-03', status: 'Present', inTime: '07:40 AM', outTime: '05:45 PM', workedHours: '10.08', remarks: 'Client meeting RTA' },
    ],
  },
  {
    employeeId: 'NRC002',
    records: [
      { date: '2026-09-01', status: 'Present', inTime: '06:45 AM', outTime: '05:30 PM', workedHours: '10.75', remarks: 'Al Khail Rd resurfacing' },
      { date: '2026-09-02', status: 'Present', inTime: '06:50 AM', outTime: '05:40 PM', workedHours: '10.83', remarks: '' },
      { date: '2026-09-03', status: 'Absent', inTime: '-', outTime: '-', workedHours: '0', remarks: 'Sick Leave' },
    ],
  },
  {
    employeeId: 'NRC003',
    records: [
      { date: '2026-09-01', status: 'Present', inTime: '08:00 AM', outTime: '05:00 PM', workedHours: '9', remarks: '' },
      { date: '2026-09-02', status: 'On Leave', inTime: '-', outTime: '-', workedHours: '0', remarks: 'Annual Leave' },
      { date: '2026-09-03', status: 'Present', inTime: '08:05 AM', outTime: '05:10 PM', workedHours: '9.08', remarks: 'BOQ review' },
    ],
  },
  {
    employeeId: 'NRC004',
    records: [
      { date: '2026-09-01', status: 'Present', inTime: '06:30 AM', outTime: '06:00 PM', workedHours: '11.5', remarks: 'Paver operation' },
      { date: '2026-09-02', status: 'Present', inTime: '06:30 AM', outTime: '06:15 PM', workedHours: '11.75', remarks: '' },
      { date: '2026-09-03', status: 'Present', inTime: '06:35 AM', outTime: '06:00 PM', workedHours: '11.42', remarks: 'Night shift prep' },
    ],
  },
];

export const NABLUS_LEDGER_ENTRIES = [
  { date: '2026-08-01', account: 'Cash', transaction_type: 'Payment', description: 'Progress payment — Dubai Municipality (Al Khail Rd)', debit: 185000, credit: null, balance: 185000 },
  { date: '2026-08-05', account: 'Accounts Receivable', transaction_type: 'Invoice', description: 'Invoice NRC-INV-2026-0142 — RTA Dubai resurfacing', debit: 246750, credit: null, balance: 246750 },
  { date: '2026-08-08', account: 'Cash', transaction_type: 'Expense', description: 'Bitumen purchase — National Asphalt Co.', debit: null, credit: 48500, balance: 136500 },
  { date: '2026-08-12', account: 'Sales Revenue', transaction_type: 'Invoice', description: 'Asphalt paving — Emaar Community Roads Phase 2', debit: null, credit: 92000, balance: -92000 },
  { date: '2026-08-15', account: 'Accounts Payable', transaction_type: 'Purchase', description: 'Crushed aggregate — Al Futtaim Building Materials', debit: null, credit: 22500, balance: -22500 },
  { date: '2026-08-20', account: 'Cash', transaction_type: 'Payment', description: 'Received from Emaar Properties PJSC', debit: 92000, credit: null, balance: 228500 },
  { date: '2026-08-25', account: 'Cash', transaction_type: 'Expense', description: 'Plant fuel & diesel — site fleet', debit: null, credit: 12800, balance: 215700 },
  { date: '2026-08-28', account: 'Accounts Receivable', transaction_type: 'Invoice', description: 'Invoice NRC-INV-2026-0158 — Sheikh Zayed Rd patching', debit: 67500, credit: null, balance: 314250 },
];

export const NABLUS_WAREHOUSE_MATERIALS = [
  {
    id: 'NRC-MAT-001',
    name: 'Asphalt Mix Hot (Wearing Course)',
    category: 'Asphalt',
    quantity: 120,
    unit: 'TON',
    barcode: 'ASPWEAR01',
    properties: {
      isFragile: false,
      requiresTemperatureControl: true,
      dimensions: { length: 100, width: 100, height: 80 },
      weight: 1000,
    },
    supplier: 'National Asphalt Co. LLC',
    poReference: 'PO-NRC-2026-041',
  },
  {
    id: 'NRC-MAT-002',
    name: 'Steel Rebar 16mm',
    category: 'Steel',
    quantity: 25,
    unit: 'TON',
    barcode: 'STL16MM01',
    properties: {
      isFragile: false,
      requiresTemperatureControl: false,
      dimensions: { length: 1200, width: 50, height: 50 },
      weight: 1000,
    },
    supplier: 'Al Futtaim Building Materials',
    poReference: 'PO-NRC-2026-042',
  },
  {
    id: 'NRC-MAT-003',
    name: 'Road Marking Paint - White',
    category: 'Consumables',
    quantity: 200,
    unit: 'LTR',
    barcode: 'RMPWHT01',
    properties: {
      isFragile: true,
      requiresTemperatureControl: false,
      dimensions: { length: 30, width: 30, height: 40 },
      weight: 5,
    },
    supplier: 'Gulf Safety Supplies LLC',
    poReference: 'PO-NRC-2026-043',
  },
];

/** Main accounting dashboard KPIs & charts (used when API is empty/unavailable). */
export const NABLUS_DASHBOARD = {
  reports: {
    total_items: 28,
    total_parties: 12,
    bank_balance: 428650.5,
    cash_balance: 18500.0,
    receivables: 314250.0,
    payables: 71000.0,
  },
  recent_transactions: [
    { date: '2026-09-12', type: 'Sales Invoice', party_name: 'RTA Dubai', amount: '246750.000' },
    { date: '2026-09-10', type: 'Payment In', party_name: 'Emaar Properties PJSC', amount: '92000.000' },
    { date: '2026-09-08', type: 'Purchase Invoice', party_name: 'National Asphalt Co. LLC', amount: '48500.000' },
    { date: '2026-09-05', type: 'Sales Invoice', party_name: 'Dubai Municipality - Roads', amount: '185000.000' },
    { date: '2026-09-03', type: 'Payment Out', party_name: 'Al Futtaim Building Materials', amount: '22500.000' },
  ],
  weekly_sales: [
    { weekday: 'Saturday', total_day_sales: 18500, invoice_count: 1 },
    { weekday: 'Sunday', total_day_sales: 0, invoice_count: 0 },
    { weekday: 'Monday', total_day_sales: 67500, invoice_count: 2 },
    { weekday: 'Tuesday', total_day_sales: 92000, invoice_count: 1 },
    { weekday: 'Wednesday', total_day_sales: 246750, invoice_count: 3 },
    { weekday: 'Thursday', total_day_sales: 48500, invoice_count: 1 },
    { weekday: 'Friday', total_day_sales: 112000, invoice_count: 2 },
  ],
  expense_income: [
    { date: 'Mon', day: 'Mon', total_income: 67500, total_expense: 12800 },
    { date: 'Tue', day: 'Tue', total_income: 92000, total_expense: 22500 },
    { date: 'Wed', day: 'Wed', total_income: 246750, total_expense: 48500 },
    { date: 'Thu', day: 'Thu', total_income: 48500, total_expense: 8500 },
    { date: 'Fri', day: 'Fri', total_income: 112000, total_expense: 15200 },
    { date: 'Sat', day: 'Sat', total_income: 18500, total_expense: 4200 },
    { date: 'Sun', day: 'Sun', total_income: 0, total_expense: 0 },
  ],
};

/** Payroll dashboard demo for Nablus Road Contracting. */
export const NABLUS_PAYROLL_DASHBOARD = {
  kpis: {
    total_employees: 48,
    total_employees_change_label: '+3 this month',
    total_payroll_formatted: 'AED 286,400.00',
    total_payroll_change_label: '+4.2% vs last month',
    total_payroll_is_estimated: false,
    attendance_rate: 94.5,
    attendance_rate_change_label: '+1.2%',
    pending_approvals: 4,
    pending_approvals_change_label: '2 leave · 2 loans',
    pending_approvals_breakdown: { leave: 2, loans: 2 },
    leave_requests: {
      all_time_approved: 142,
      all_time_total: 168,
    },
  },
  leave_request_summary: {
    financial_year: {
      pending: 2,
      approved: 18,
      rejected: 1,
      total: 21,
      period_start: '01 Jan 2026',
      period_end: '31 Dec 2026',
    },
    financial_year_by_category: {
      paid_approved: [
        { name: 'Annual', count: 10 },
        { name: 'Sick', count: 5 },
        { name: 'Unpaid', count: 2 },
        { name: 'Maternity', count: 1 },
      ],
    },
  },
  payroll_trend: [
    { month: 'Apr', amount: 268000 },
    { month: 'May', amount: 272500 },
    { month: 'Jun', amount: 275000 },
    { month: 'Jul', amount: 280200 },
    { month: 'Aug', amount: 274800 },
    { month: 'Sep', amount: 286400 },
  ],
  attendance_overview: [
    { day: 'Sat', date: '2026-09-06', attendance_rate: 88 },
    { day: 'Sun', date: '2026-09-07', attendance_rate: 0 },
    { day: 'Mon', date: '2026-09-08', attendance_rate: 96 },
    { day: 'Tue', date: '2026-09-09', attendance_rate: 94 },
    { day: 'Wed', date: '2026-09-10', attendance_rate: 97 },
    { day: 'Thu', date: '2026-09-11', attendance_rate: 95 },
    { day: 'Fri', date: '2026-09-12', attendance_rate: 92 },
  ],
  leave_balance_summary: [
    { name: 'Annual Leave', used: 86, total: 240, remaining: 154, label: 'Annual' },
    { name: 'Sick Leave', used: 22, total: 90, remaining: 68, label: 'Sick' },
    { name: 'Unpaid Leave', used: 8, total: 40, remaining: 32, label: 'Unpaid' },
  ],
  recent_pay_runs: [
    {
      pay_run_id: 101,
      payroll_run_id: 'PR-2026-09',
      period: 'Sep 2026',
      employees: 48,
      amount: 286400,
      amount_formatted: 'AED 286,400.00',
      status: 'Processed',
    },
    {
      pay_run_id: 100,
      payroll_run_id: 'PR-2026-08',
      period: 'Aug 2026',
      employees: 45,
      amount: 274800,
      amount_formatted: 'AED 274,800.00',
      status: 'Paid',
    },
  ],
  upcoming_schedules: [
    { schedule: 'Monthly — Site Staff', next_run: '2026-09-28', next_run_formatted: '28 Sep 2026', employees: 32 },
    { schedule: 'Monthly — Office Staff', next_run: '2026-09-28', next_run_formatted: '28 Sep 2026', employees: 16 },
  ],
  department_breakdown: [
    { department: 'Site Operations', employee_count: 22 },
    { department: 'Plant & Machinery', employee_count: 10 },
    { department: 'Projects', employee_count: 6 },
    { department: 'Estimation', employee_count: 4 },
    { department: 'Accounts', employee_count: 3 },
    { department: 'HR', employee_count: 3 },
  ],
  active_loans: [
    { employee: 'Hassan Mansour', amount: 15000, remaining: 9000, installments: '6/10' },
    { employee: 'Mohammed Yousef', amount: 5000, remaining: 2500, installments: '5/10' },
  ],
};

/** Warehouse dashboard demo — Al Quoz materials yard. */
export const NABLUS_WAREHOUSE_DASHBOARD = {
  kpis: {
    warehouses: 2,
    rack_locations: 48,
    total_stock_items: 28,
    outward_transactions: 14,
  },
  process_flow_counts: {
    loading_bay: 3,
    putaway_tasks: 5,
    rack_storage: 28,
    rack_movement: 2,
    picking_tasks: 4,
    dispatch: 3,
  },
  process_flow: {
    putaway_tasks_pending: 5,
    rack_movements_pending: 2,
    picking_tasks_pending: 4,
    loading_bay_utilization_percent: 62,
  },
  putaway_statistics: {
    by_putaway_status: [
      { putaway_status: 'Completed', count: 18 },
      { putaway_status: 'In Progress', count: 3 },
      { putaway_status: 'Pending', count: 5 },
    ],
  },
  picking_statistics: { pending: 4, in_progress: 2, completed: 12 },
  rack_movements_statistics: { pending: 2, in_progress: 1, completed: 9 },
  loading_bay_status: [
    { bay: 'Bay A — Aggregate', status: 'Occupied', utilization: 80 },
    { bay: 'Bay B — Asphalt Hot Mix', status: 'Occupied', utilization: 65 },
    { bay: 'Bay C — Steel & Consumables', status: 'Available', utilization: 20 },
  ],
  low_stock_alerts: {
    total_alerts: 3,
    critical_count: 1,
    warning_count: 2,
    items: [
      { name: 'Bitumen 60/70', quantity: 4, unit: 'TON', level: 'critical' },
      { name: 'Road Marking Paint - White', quantity: 18, unit: 'LTR', level: 'warning' },
      { name: 'Crushed Aggregate 20mm', quantity: 35, unit: 'TON', level: 'warning' },
    ],
  },
  recent_activity: [
    { time: '09:40', action: 'Inward', detail: 'Asphalt Mix 40 TON from National Asphalt Co.', user: 'Hassan Mansour' },
    { time: '11:15', action: 'Putaway', detail: 'Steel Rebar 16mm → Rack R-12', user: 'Mohammed Yousef' },
    { time: '13:05', action: 'Pick', detail: 'Wearing Course 25 TON for Al Khail Rd site', user: 'Omar Al Hashimi' },
    { time: '15:30', action: 'Dispatch', detail: 'DN-NRC-089 → Sheikh Zayed Rd patching', user: 'Carlos Mendoza' },
  ],
  fast_moving_items: [
    { name: 'Asphalt Mix Hot (Wearing Course)', quantity: 120, unit: 'TON' },
    { name: 'Crushed Aggregate 20mm', quantity: 85, unit: 'TON' },
    { name: 'Bitumen 60/70', quantity: 12, unit: 'TON' },
  ],
  slow_moving_items: [
    { name: 'Concrete Grade C40', quantity: 8, unit: 'M3' },
    { name: 'Steel Rebar 16mm', quantity: 6, unit: 'TON' },
  ],
};
